### ISSUE TITLE
ValueError in _form_exciton() method

### ISSUE THREAD

**Issue by Pehnny** [Pehnny/hyperfluorescence#12]
ValueError occured inside the `_form_exciton()` method of the Lattice class :

```python
Traceback (most recent call last):
  File "/home/tpiron/maxoled/reseau.py", line 793, in operations
    running = self._first_reaction_method()
  File "/home/tpiron/maxoled/reseau.py", line 727, in _first_reaction_method
    self._form_exciton(event.final)
  File "/home/tpiron/maxoled/reseau.py", line 618, in _form_exciton
    self._holes_locations.remove(position)
ValueError: list.remove(x): x not in list
5920 1200 80

deque([
    Event(initial=Point(x=19, y=19, z=15), final=Point(x=19, y=18, z=14), tau=0.0, kind=1, particule=1), 
    Event(initial=Point(x=19, y=18, z=14), final=Point(x=19, y=19, z=15), tau=0.0, kind=1, particule=1), 
    Event(initial=Point(x=19, y=19, z=15), final=Point(x=19, y=18, z=14), tau=0.0, kind=1, particule=1), 
    Event(initial=Point(x=19, y=18, z=14), final=Point(x=19, y=19, z=15), tau=0.0, kind=1, particule=1), 
    Event(initial=Point(x=7, y=4, z=12), final=Point(x=7, y=5, z=12), tau=0.0, kind=1, particule=1), 
    Event(initial=Point(x=7, y=5, z=12), final=Point(x=6, y=6, z=12), tau=0.0, kind=1, particule=1), 
    Event(initial=Point(x=19, y=19, z=15), final=Point(x=19, y=18, z=14), tau=0.0, kind=1, particule=1), 
    Event(initial=Point(x=6, y=6, z=12), final=Point(x=5, y=6, z=11), tau=0.0, kind=1, particule=1), 
    Event(initial=Point(x=5, y=6, z=11), final=Point(x=5, y=6, z=10), tau=0.0, kind=1, particule=1), 
    Event(initial=Point(x=5, y=6, z=10), final=Point(x=5, y=6, z=10), tau=0.0, kind=2, particule=3)
], maxlen=10) 

electrons :  4 [
    Point(x=19, y=6, z=18), 
    Point(x=6, y=18, z=16), 
    Point(x=15, y=16, z=11), 
    Point(x=19, y=18, z=14)
] 

holes :  4 [
    Point(x=13, y=2, z=4), 
    Point(x=17, y=15, z=3), 
    Point(x=7, y=0, z=2), 
    Point(x=11, y=9, z=9)
] 

excitons :  1 [
    Point(x=5, y=6, z=10)
] 

move events :  0 [] 

exciton events :  2 [
    Event(initial=Point(x=5, y=6, z=10), final=Point(x=6, y=7, z=9), tau=5.1153914184466356e-06, kind=7, particule=1), 
    Event(initial=Point(x=5, y=6, z=10), final=Point(x=5, y=6, z=10), tau=0.0, kind=2, particule=3)
] 

fluorophores :  80 [Point(x=7, y=1, z=1), Point(x=10, y=1, z=1), Point(x=5, y=5, z=1), Point(x=10, y=16, z=1), Point(x=7, y=0, z=2), Point(x=18, y=3, z=2), Point(x=18, y=5, z=2), Point(x=3, y=9, z=2), Point(x=0, y=10, z=2), Point(x=5, y=11, z=2), Point(x=19, y=1, z=3), Point(x=17, y=15, z=3), Point(x=9, y=0, z=4), Point(x=13, y=2, z=4), Point(x=3, y=5, z=4), Point(x=3, y=9, z=4), Point(x=2, y=11, z=4), Point(x=19, y=11, z=4), Point(x=2, y=12, z=4), Point(x=11, y=2, z=5), Point(x=4, y=19, z=5), Point(x=0, y=6, z=6), Point(x=19, y=6, z=6), Point(x=19, y=8, z=6), Point(x=4, y=14, z=6), Point(x=4, y=0, z=7), Point(x=1, y=15, z=7), Point(x=0, y=17, z=7), Point(x=5, y=2, z=8), Point(x=3, y=16, z=8), Point(x=9, y=18, z=8), Point(x=18, y=5, z=9), Point(x=14, y=6, z=9), Point(x=6, y=10, z=9), Point(x=5, y=12, z=9), Point(x=8, y=14, z=9), Point(x=13, y=14, z=9), Point(x=8, y=2, z=10), Point(x=5, y=6, z=10), Point(x=15, y=6, z=10), Point(x=19, y=17, z=10), Point(x=9, y=19, z=10), Point(x=19, y=19, z=10), Point(x=11, y=5, z=11), Point(x=0, y=9, z=11), Point(x=10, y=11, z=11), Point(x=18, y=16, z=11), Point(x=4, y=17, z=11), Point(x=10, y=18, z=11), Point(x=7, y=4, z=12), Point(x=12, y=16, z=12), Point(x=5, y=4, z=13), Point(x=14, y=4, z=13), Point(x=12, y=12, z=13), Point(x=15, y=14, z=13), Point(x=10, y=16, z=13), Point(x=18, y=19, z=13), Point(x=8, y=3, z=14), Point(x=2, y=5, z=14), Point(x=15, y=6, z=14), Point(x=10, y=16, z=14), Point(x=0, y=19, z=14), Point(x=14, y=4, z=15), Point(x=19, y=5, z=15), Point(x=15, y=7, z=15), Point(x=9, y=8, z=15), Point(x=11, y=9, z=15), Point(x=2, y=15, z=15), Point(x=2, y=8, z=16), Point(x=7, y=10, z=16), Point(x=4, y=15, z=16), Point(x=15, y=8, z=17), Point(x=10, y=10, z=17), Point(x=6, y=16, z=17), Point(x=14, y=18, z=17), Point(x=0, y=4, z=18), Point(x=15, y=6, z=18), Point(x=11, y=11, z=18), Point(x=18, y=15, z=18), Point(x=15, y=18, z=18)] 
```

**Comment by Pehnny** [comment]
The important part of the issue is :
```python
exciton events :  2 [
    Event(initial=Point(x=5, y=6, z=10), final=Point(x=6, y=7, z=9), tau=5.1153914184466356e-06, kind=7, particule=1), 
    Event(initial=Point(x=5, y=6, z=10), final=Point(x=5, y=6, z=10), tau=0.0, kind=2, particule=3)
] 
```
I managed to reproduce it 5 times and it's always the same : 
```python
exciton events :  2 [
    Event(initial=Point(x=4, y=13, z=15), final=Point(x=5, y=13, z=15), tau=3.1672181124660812e-09, kind=7, particule=2), 
    Event(initial=Point(x=4, y=13, z=15), final=Point(x=4, y=13, z=15), tau=0.0, kind=2, particule=3)
] 

exciton events :  2 [
    Event(initial=Point(x=2, y=10, z=18), final=Point(x=1, y=10, z=18), tau=5.844104105633116e-08, kind=7, particule=2), 
    Event(initial=Point(x=2, y=10, z=18), final=Point(x=2, y=10, z=18), tau=0.0, kind=2, particule=3)
] 

exciton events :  2 [
    Event(initial=Point(x=18, y=12, z=10), final=Point(x=18, y=12, z=11), tau=5.2878221821411635e-09, kind=7, particule=1), 
    Event(initial=Point(x=18, y=12, z=10), final=Point(x=18, y=12, z=10), tau=0.0, kind=2, particule=3)
] 

exciton events :  2 [
    Event(initial=Point(x=6, y=12, z=14), final=Point(x=6, y=11, z=13), tau=2.9107814432782426e-06, kind=7, particule=1), 
    Event(initial=Point(x=6, y=12, z=14), final=Point(x=6, y=12, z=14), tau=0.0, kind=2, particule=3)
] 

exciton events :  2 [
    Event(initial=Point(x=16, y=17, z=16), final=Point(x=16, y=16, z=17), tau=4.944802425598186e-06, kind=7, particule=1), 
    Event(initial=Point(x=16, y=17, z=16), final=Point(x=16, y=17, z=16), tau=0.0, kind=2, particule=3)
] 
```
An exciton is not supposed to form on an occupied molecule. I think this occures because it only checks for electrons and holes locations when creating a new move event but the locations are removed when an exciton forms.

A simple solution should be to check for both electrons/holes and excitons locations to prevent a move event toward a molecule occupied by an exciton shouldn't happen anymore, fixing the error.
