### ISSUE TITLE
ZeroDivisionError encountered in the time_energy_transfer() method of Lattice class

### ISSUE THREAD

**Issue by Pehnny** [Pehnny/hyperfluorescence#13]
_2 sleepy 2 write, just posting this and going to bed_
```python
Traceback (most recent call last):
  File "/home/tpiron/303010/reseau.py", line 772, in operations
    running = self._first_reaction_method()
  File "/home/tpiron/303010/reseau.py", line 700, in _first_reaction_method
    self._new_TADF_event(event.final, molecule.exciton)
  File "/home/tpiron/303010/reseau.py", line 524, in _new_TADF_event
    ] + [
  File "/home/tpiron/303010/reseau.py", line 525, in <listcomp>
    Event(position, transfer, self._time_energy_transfer(position, transfer, spin), EVENTS["ET"], PARTICULES["exciton"])
  File "/home/tpiron/303010/reseau.py", line 335, in _time_energy_transfer
    return - log(rng) / transfer_rate
ZeroDivisionError: float division by zero


 deque([Event(initial=Point(x=0, y=23, z=4), final=Point(x=0, y=23, z=5), tau=0.0, kind=1, particule=2), Event(initial=Point(x=0, y=23, z=5), final=Point(x=0, y=23, z=6), tau=0.0, kind=1, particule=2), Event(initial=Point(x=2, y=0, z=5), final=Point(x=1, y=0, z=5), tau=0.0, kind=1, particule=2), Event(initial=Point(x=8, y=4, z=6), final=Point(x=8, y=4, z=7), tau=0.0, kind=1, particule=2), Event(initial=Point(x=8, y=4, z=7), final=Point(x=9, y=4, z=7), tau=0.0, kind=1, particule=2), Event(initial=Point(x=1, y=0, z=5), final=Point(x=2, y=0, z=5), tau=0.0, kind=1, particule=2), Event(initial=Point(x=9, y=4, z=7), final=Point(x=9, y=3, z=7), tau=0.0, kind=1, particule=2), Event(initial=Point(x=9, y=3, z=7), final=Point(x=9, y=3, z=8), tau=0.0, kind=1, particule=2), Event(initial=Point(x=27, y=27, z=5), final=Point(x=28, y=28, z=5), tau=0.0, kind=1, particule=1), Event(initial=Point(x=28, y=28, z=5), final=Point(x=28, y=28, z=5), tau=0.0, kind=2, particule=3)], maxlen=10) 

electrons :  7 [Point(x=9, y=2, z=8), Point(x=28, y=0, z=8), Point(x=19, y=26, z=8), Point(x=21, y=8, z=7), Point(x=14, y=21, z=5), Point(x=2, y=2, z=6), Point(x=24, y=20, z=7)] 

holes :  7 [Point(x=4, y=18, z=6), Point(x=2, y=22, z=7), Point(x=9, y=18, z=5), Point(x=1, y=27, z=4), Point(x=0, y=23, z=6), Point(x=2, y=0, z=5), Point(x=9, y=3, z=8)] 

excitons :  1 [Point(x=28, y=28, z=5)] 

move events :  0 [] 

exciton events :  0 [] 

capture events :  0 [] 

fluorophores :  90 [Point(x=6, y=2, z=1), Point(x=12, y=4, z=1), Point(x=9, y=6, z=1), Point(x=19, y=6, z=1), Point(x=19, y=7, z=1), Point(x=22, y=8, z=1), Point(x=25, y=8, z=1), Point(x=26, y=8, z=1), Point(x=19, y=10, z=1), Point(x=22, y=14, z=1), Point(x=14, y=16, z=1), Point(x=8, y=19, z=1), Point(x=13, y=19, z=1), Point(x=19, y=20, z=1), Point(x=25, y=21, z=1), Point(x=11, y=23, z=1), Point(x=9, y=24, z=1), Point(x=22, y=27, z=1), Point(x=6, y=2, z=2), Point(x=0, y=3, z=2), Point(x=17, y=3, z=2), Point(x=25, y=4, z=2), Point(x=16, y=10, z=2), Point(x=8, y=13, z=2), Point(x=24, y=14, z=2), Point(x=5, y=15, z=2), Point(x=15, y=15, z=2), Point(x=14, y=16, z=2), Point(x=5, y=17, z=2), Point(x=18, y=17, z=2), Point(x=12, y=18, z=2), Point(x=12, y=19, z=2), Point(x=24, y=20, z=2), Point(x=15, y=21, z=2), Point(x=8, y=23, z=2), Point(x=27, y=24, z=2), Point(x=16, y=26, z=2), Point(x=25, y=26, z=2), Point(x=13, y=1, z=3), Point(x=29, y=1, z=3), Point(x=17, y=4, z=3), Point(x=24, y=5, z=3), Point(x=17, y=7, z=3), Point(x=17, y=8, z=3), Point(x=27, y=16, z=3), Point(x=28, y=16, z=3), Point(x=16, y=21, z=3), Point(x=12, y=25, z=3), Point(x=19, y=25, z=3), Point(x=18, y=29, z=3), Point(x=0, y=4, z=4), Point(x=14, y=5, z=4), Point(x=25, y=6, z=4), Point(x=8, y=8, z=4), Point(x=4, y=15, z=4), Point(x=19, y=25, z=4), Point(x=28, y=25, z=4), Point(x=2, y=29, z=4), Point(x=26, y=29, z=4), Point(x=22, y=4, z=5), Point(x=28, y=4, z=5), Point(x=25, y=5, z=5), Point(x=26, y=5, z=5), Point(x=3, y=7, z=5), Point(x=17, y=18, z=5), Point(x=8, y=21, z=5), Point(x=10, y=21, z=5), Point(x=13, y=23, z=5), Point(x=27, y=23, z=5), Point(x=1, y=24, z=5), Point(x=23, y=24, z=5), Point(x=21, y=0, z=6), Point(x=7, y=9, z=6), Point(x=19, y=9, z=6), Point(x=3, y=10, z=6), Point(x=2, y=16, z=6), Point(x=12, y=17, z=6), Point(x=12, y=20, z=6), Point(x=25, y=25, z=6), Point(x=16, y=29, z=6), Point(x=14, y=12, z=7), Point(x=28, y=21, z=7), Point(x=2, y=22, z=7), Point(x=15, y=25, z=7), Point(x=28, y=0, z=8), Point(x=4, y=3, z=8), Point(x=17, y=5, z=8), Point(x=4, y=18, z=8), Point(x=22, y=19, z=8), Point(x=4, y=20, z=8)] 
```

**Comment by Pehnny** [comment]
I don't remember but I fixed this
